apiVersion: v1
kind: Secret
metadata:
  name: biomarine-secrets
  namespace: biomarine
type: Opaque
stringData:
  JWT_SECRET: "replace-with-strong-secret"
  AWS_ACCESS_KEY_ID: "AKIATSRRZTFQTZG7AT2P"
  AWS_SECRET_ACCESS_KEY: "repll7mnVWBu1rpPeYy81tAbMRVOpQPTMHUjace"
  GOOGLE_CLIENT_ID: "replace"
  GOOGLE_CLIENT_SECRET: "replace"
  LINKEDIN_CLIENT_ID: "replace"
  LINKEDIN_CLIENT_SECRET: "replace"

